// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/Account/ActivateUser": {
            "post": {
                "security": [
                    {
                        "bearer": []
                    }
                ],
                "tags": [
                    "Account"
                ],
                "summary": "Activate User by Code",
                "parameters": [
                    {
                        "description": "ActivationData",
                        "name": "ActivateUser",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ActivationByCode.ActivationByCodeCommand"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Common.ResponseModel-string"
                        }
                    }
                }
            }
        },
        "/Account/ForgetPassword": {
            "post": {
                "security": [
                    {
                        "bearer": []
                    }
                ],
                "tags": [
                    "Account"
                ],
                "summary": "Register an User",
                "parameters": [
                    {
                        "description": "ForgetPassword",
                        "name": "ForgetPassword",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ForgetPassword.ForgetPasswordCommand"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Common.ResponseModel-string"
                        }
                    }
                }
            }
        },
        "/Account/Register": {
            "post": {
                "security": [
                    {
                        "bearer": []
                    }
                ],
                "tags": [
                    "Account"
                ],
                "summary": "Register an User",
                "parameters": [
                    {
                        "description": "RegisterData",
                        "name": "register",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Register.RegisterCommand"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Common.ResponseModel-string"
                        }
                    }
                }
            }
        },
        "/Categories/GetCategories": {
            "get": {
                "security": [
                    {
                        "bearer": []
                    }
                ],
                "tags": [
                    "Account"
                ],
                "summary": "Register an User",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Parent Id",
                        "name": "parentId",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Common.ResponseModel-GetCategories_GetCategoriesVm"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "ActivationByCode.ActivationByCodeCommand": {
            "type": "object",
            "properties": {
                "activationCode": {
                    "type": "integer"
                }
            }
        },
        "Common.ResponseModel-GetCategories_GetCategoriesVm": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/GetCategories.GetCategoriesVm"
                },
                "message": {
                    "type": "string"
                },
                "statusCode": {
                    "type": "integer"
                }
            }
        },
        "Common.ResponseModel-string": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "statusCode": {
                    "type": "integer"
                }
            }
        },
        "ForgetPassword.ForgetPasswordCommand": {
            "type": "object",
            "properties": {
                "phoneNumber": {
                    "type": "integer"
                }
            }
        },
        "GetCategories.GetCategoriesVm": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "likeCount": {
                    "type": "integer"
                },
                "parentCatId": {
                    "type": "integer"
                },
                "summary": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "Register.RegisterCommand": {
            "type": "object",
            "properties": {
                "Password": {
                    "type": "string"
                },
                "PhoneNumber": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "bearer": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0// @host localhost:8080",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
